### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Minesound** [NSS-Robotics/website#275]
I am interested in your source code to build a website for commercial and personal ends. However, I couldn't find any licensing info, so I assume that it is all rights reserved and only for educational fair use (and display)? Would you mind clarifying the licensing situation? Thanks!

**Comment by Orbitally** [comment]
Hey, sorry for the late response. I just put the project under the MPL-2.0 license so you're more than welcome to use the code for your project! I really appreciate you asking for the clarification and sorry again for the long response time.
